-- MySQL Script generated by MySQL Workbench
-- Sat Aug 24 12:35:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jpa1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jpa1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jpa1` DEFAULT CHARACTER SET utf8 ;
USE `jpa1` ;

-- -----------------------------------------------------
-- Table `jpa1`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jpa1`.`Endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rua` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(20) NOT NULL,
  `uf` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jpa1`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jpa1`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `Endereco_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cliente_Endereco_idx` (`Endereco_id` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Endereco`
    FOREIGN KEY (`Endereco_id`)
    REFERENCES `jpa1`.`Endereco` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jpa1`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jpa1`.`Pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `Cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `jpa1`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jpa1`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jpa1`.`Produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jpa1`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jpa1`.`Item` (
  `Pedido_id` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`Pedido_id`, `Produto_id`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`Produto_id` ASC) VISIBLE,
  INDEX `fk_Pedido_has_Produto_Pedido1_idx` (`Pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_has_Produto_Pedido1`
    FOREIGN KEY (`Pedido_id`)
    REFERENCES `jpa1`.`Pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `jpa1`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
